export const METRO_LINES = [
  "METRO 1",
  "METRO 2",
  "METRO 3",
  "METRO 3bis",
  "METRO 4",
  "METRO 5",
  "METRO 6",
  "METRO 7",
  "METRO 7bis",
  "METRO 8",
  "METRO 9",
  "METRO 10",
  "METRO 11",
  "METRO 12",
  "METRO 13",
  "METRO 14",
];

export const LINES: {
  [name: string]: {
    name: string;
    color: string;
    backgroundColor: string;
    textColor: string;
    order: number;
  };
} = {
  "METRO 1": {
    name: "1",
    color: "#ffce00",
    backgroundColor: "#806700",
    textColor: "#222",
    order: 1,
  },
  "METRO 2": {
    name: "2",
    color: "#0064b0",
    backgroundColor: "#003258",
    textColor: "#fff",
    order: 2,
  },
  "METRO 3": {
    name: "3",
    color: "#9f9825",
    backgroundColor: "#4f4c12",
    textColor: "#fff",
    order: 3,
  },
  "METRO 3bis": {
    name: "3b",
    color: "#98d4e2",
    backgroundColor: "#2a7f93",
    textColor: "#222",
    order: 3.5,
  },
  "METRO 4": {
    name: "4",
    color: "#c04191",
    backgroundColor: "#602049",
    textColor: "#fff",
    order: 4,
  },
  "METRO 5": {
    name: "5",
    color: "#f28e42",
    backgroundColor: "#90440a",
    textColor: "#222",
    order: 5,
  },
  "METRO 6": {
    name: "6",
    color: "#83c491",
    backgroundColor: "#356f41",
    textColor: "#222",
    order: 6,
  },
  "METRO 7": {
    name: "7",
    color: "#f3a4ba",
    backgroundColor: "#b41843",
    textColor: "#222",
    order: 7,
  },
  "METRO 7bis": {
    name: "7b",
    color: "#83c491",
    backgroundColor: "#356f41",
    textColor: "#222",
    order: 7.5,
  },
  "METRO 8": {
    name: "8",
    color: "#ceadd2",
    backgroundColor: "#76447c",
    textColor: "#222",
    order: 8,
  },
  "METRO 9": {
    name: "9",
    color: "#d5c900",
    backgroundColor: "#6a6400",
    textColor: "#222",
    order: 9,
  },
  "METRO 10": {
    name: "10",
    color: "#e3b32a",
    backgroundColor: "#775c10",
    textColor: "#222",
    order: 10,
  },
  "METRO 11": {
    name: "11",
    color: "#8d5e2a",
    backgroundColor: "#462f15",
    textColor: "#fff",
    order: 11,
  },
  "METRO 12": {
    name: "12",
    color: "#00814f",
    backgroundColor: "#004027",
    textColor: "#fff",
    order: 12,
  },
  "METRO 13": {
    name: "13",
    color: "#98d4e2",
    backgroundColor: "#2a7f93",
    textColor: "#222",
    order: 13,
  },
  "METRO 14": {
    name: "14",
    color: "#662483",
    backgroundColor: "#331241",
    textColor: "#fff",
    order: 14,
  },
  // @todo from here it's dummy data
  "RER A": {
    name: "A",
    color: "#d9006c",
    backgroundColor: "#6c001f",
    textColor: "#fff",
    order: 1,
  },
  "RER B": {
    name: "B",
    color: "#0064b0",
    backgroundColor: "#003258",
    textColor: "#fff",
    order: 2,
  },
  "RER C": {
    name: "C",
    color: "#9f9825",
    backgroundColor: "#4f4c12",
    textColor: "#fff",
    order: 3,
  },
  "RER D": {
    name: "D",
    color: "green",
    backgroundColor: "#602049",
    textColor: "#fff",
    order: 4,
  },
  "RER E": {
    name: "E",
    color: "pink",
    backgroundColor: "#90440a",
    textColor: "#222",
    order: 5,
  },
  "TRAM 2": {
    name: "T2",
    color: "orange",
    backgroundColor: "#356f41",
    textColor: "#222",
    order: 6,
  },
  "TRAM 3": {
    name: "T3",
    color: "blue",
    backgroundColor: "#356f41",
    textColor: "#222",
    order: 6,
  },
  "TRAM 3a": {
    name: "T3a",
    color: "blue",
    backgroundColor: "#356f41",
    textColor: "#222",
    order: 6,
  },
  "TRAIN N": {
    name: "N",
    color: "blue",
    backgroundColor: "#356f41",
    textColor: "#fff",
    order: 6,
  },
  "TRAIN L": {
    name: "L",
    color: "magenta",
    backgroundColor: "#356f41",
    textColor: "#fff",
    order: 6,
  },
  "TRAIN U": {
    name: "U",
    color: "purple",
    backgroundColor: "#356f41",
    textColor: "#fff",
    order: 6,
  },
};

export const MODE_NAMES: { [key: string]: string } = {
  METRO: "métro",
  RER: "RER",
  TRAM: "tramway",
  TRAIN: "train",
  OTHER: "autres",
};
